// Package vector implements msgvault's semantic and hybrid search over
// the email corpus. Embeddings are generated by an external
// OpenAI-compatible endpoint; vectors are stored in a separate
// ~/.msgvault/vectors.db. See docs/superpowers/specs/2026-04-19-vector-search-design.md.
package vector

import (
	"errors"
	"fmt"
	"net/url"
	"strings"
	"time"
)

// preprocessVersion identifies the embed/preprocess.go implementation
// generation. Bump whenever a change to that file produces a different
// Preprocess() output for the same PreprocessConfig flags — for
// example: tightening a regex, adding a tracking-param key, or adding
// a new default-on transform. Combined with the effective flag tuple
// in PreprocessConfig.Fingerprint, it makes Config.GenerationFingerprint
// invalidate any index built under a different preprocessing policy so
// the operator must --full-rebuild rather than silently mixing
// inconsistently-prepared vectors in one generation.
const preprocessVersion = 1

// embedPolicyVersion identifies the embed-worker output layout for a
// given Preprocess result. Bump whenever a change to internal/vector/
// embed/worker.go (or its chunking helpers) would shift the set of
// vectors written for the same Preprocess output — for example: the
// switch from single-vector-per-message to multi-chunk-per-message, a
// change to the chunk window/overlap derivation, or a change to the
// per-message chunk cap. Like preprocessVersion this is folded into
// GenerationFingerprint so flipping the policy stales the active
// index and forces --full-rebuild rather than mixing single-vector
// and chunked entries inside one generation.
//
// v1: chunked layout (the worker passes maxChars=0 to Preprocess and
// splits the result into MaxInputChars-bounded chunks via ChunkText).
const embedPolicyVersion = 1

// Config is the top-level vector-search configuration, loaded from the
// [vector] TOML table.
type Config struct {
	Enabled    bool             `toml:"enabled"`
	Backend    string           `toml:"backend"` // "sqlite-vec" or "pgvector"; concrete backend is DSN-selected
	DBPath     string           `toml:"db_path"` // backend-specific
	Embeddings EmbeddingsConfig `toml:"embeddings"`
	Preprocess PreprocessConfig `toml:"preprocess"`
	Search     SearchConfig     `toml:"search"`
	Embed      EmbedConfig      `toml:"embed"`

	// SkipExtensionCreate skips the `CREATE EXTENSION IF NOT EXISTS
	// vector` step on the pgvector backend while still letting Migrate
	// create the schema tables and indexes. Set this on a managed or
	// locked-down PostgreSQL where the `vector` extension is installed by
	// an administrator and the msgvault role lacks the superuser privilege
	// CREATE EXTENSION requires. Ignored on the sqlite-vec backend.
	SkipExtensionCreate bool `toml:"skip_extension_create"`
}

// EmbeddingsConfig configures the external OpenAI-compatible
// embedding endpoint used to convert message text into vectors.
type EmbeddingsConfig struct {
	Endpoint      string        `toml:"endpoint"`
	APIKeyEnv     string        `toml:"api_key_env"`
	Model         string        `toml:"model"`
	Dimension     int           `toml:"dimension"`
	BatchSize     int           `toml:"batch_size"`
	Timeout       time.Duration `toml:"timeout"`
	MaxRetries    int           `toml:"max_retries"`
	MaxInputChars int           `toml:"max_input_chars"`
	ETAWindow     int           `toml:"eta_window"`
}

// PreprocessConfig controls message text preprocessing before embedding.
//
// Fields are pointers so the decoder can distinguish "unset" (nil,
// defaults to true) from an explicit `false` in the TOML file. Call the
// XxxEnabled helpers to resolve the effective value.
type PreprocessConfig struct {
	StripQuotes        *bool `toml:"strip_quotes"`
	StripSignatures    *bool `toml:"strip_signatures"`
	StripHTML          *bool `toml:"strip_html"`
	StripBase64        *bool `toml:"strip_base64"`
	StripURLTracking   *bool `toml:"strip_url_tracking"`
	CollapseWhitespace *bool `toml:"collapse_whitespace"`
}

// StripQuotesEnabled returns the effective strip_quotes setting.
// Defaults to true when the field is unset.
func (p PreprocessConfig) StripQuotesEnabled() bool {
	if p.StripQuotes == nil {
		return true
	}
	return *p.StripQuotes
}

// StripSignaturesEnabled returns the effective strip_signatures setting.
// Defaults to true when the field is unset.
func (p PreprocessConfig) StripSignaturesEnabled() bool {
	if p.StripSignatures == nil {
		return true
	}
	return *p.StripSignatures
}

// StripHTMLEnabled returns the effective strip_html setting.
// Defaults to true when the field is unset — HTML markup that leaks into
// body_text tokenizes densely (punctuation-heavy) without contributing
// semantic content.
func (p PreprocessConfig) StripHTMLEnabled() bool {
	if p.StripHTML == nil {
		return true
	}
	return *p.StripHTML
}

// StripBase64Enabled returns the effective strip_base64 setting.
// Defaults to true when the field is unset — inline base64 blobs (images,
// embedded MIME parts) inflate token counts without contributing
// retrievable meaning.
func (p PreprocessConfig) StripBase64Enabled() bool {
	if p.StripBase64 == nil {
		return true
	}
	return *p.StripBase64
}

// StripURLTrackingEnabled returns the effective strip_url_tracking setting.
// Defaults to true when the field is unset — utm_*, fbclid, etc. add no
// semantic value and make otherwise-identical URLs look distinct to the
// embedder.
func (p PreprocessConfig) StripURLTrackingEnabled() bool {
	if p.StripURLTracking == nil {
		return true
	}
	return *p.StripURLTracking
}

// CollapseWhitespaceEnabled returns the effective collapse_whitespace setting.
// Defaults to true when the field is unset — HTML→text conversion routinely
// produces runs of empty lines and double-spaces that crowd out real content
// under the max_input_chars cap.
func (p PreprocessConfig) CollapseWhitespaceEnabled() bool {
	if p.CollapseWhitespace == nil {
		return true
	}
	return *p.CollapseWhitespace
}

// Fingerprint returns a stable, debuggable identifier for the effective
// preprocessing policy. Format: "p<ver>-<flags>" where ver is the
// preprocessVersion constant (bumped on regex/policy changes inside
// internal/vector/embed/preprocess.go) and flags is a 0/1 string in
// field-declaration order: strip_quotes, strip_signatures, strip_html,
// strip_base64, strip_url_tracking, collapse_whitespace. New toggles
// append to the right so adding one cannot collide with an existing
// fingerprint by accident.
func (p PreprocessConfig) Fingerprint() string {
	flags := []bool{
		p.StripQuotesEnabled(),
		p.StripSignaturesEnabled(),
		p.StripHTMLEnabled(),
		p.StripBase64Enabled(),
		p.StripURLTrackingEnabled(),
		p.CollapseWhitespaceEnabled(),
	}
	var b strings.Builder
	b.Grow(len("p999-") + len(flags))
	fmt.Fprintf(&b, "p%d-", preprocessVersion)
	for _, on := range flags {
		if on {
			b.WriteByte('1')
		} else {
			b.WriteByte('0')
		}
	}
	return b.String()
}

// SearchConfig controls hybrid-search ranking and result limits.
//
// MaxPageSizeHybrid is a *int so an omitted field (nil) can be told
// apart from an explicit 0 in the TOML file. ApplyDefaults fills in
// 50 only when nil; explicit `max_page_size_hybrid = 0` is preserved
// and disables the per-request clamp entirely. Use the
// MaxPageSizeHybridClamp helper to read the effective value at the
// API/MCP boundary.
type SearchConfig struct {
	RRFK              int     `toml:"rrf_k"`
	KPerSignal        int     `toml:"k_per_signal"`
	SubjectBoost      float64 `toml:"subject_boost"`
	MaxPageSizeHybrid *int    `toml:"max_page_size_hybrid"`
}

// MaxPageSizeHybridClamp returns the effective per-request limit
// clamp: zero means "no clamp", a positive value means "clamp to N".
// Helper exists because callers want a flat int and need to handle
// the nil-pointer "unset" case identically to an explicit 0.
func (s SearchConfig) MaxPageSizeHybridClamp() int {
	if s.MaxPageSizeHybrid == nil {
		return 0
	}
	return *s.MaxPageSizeHybrid
}

// EmbedConfig groups embed-side concerns that aren't part of the
// embedding endpoint itself (e.g. scheduling).
type EmbedConfig struct {
	Schedule EmbedScheduleConfig `toml:"schedule"`
}

// EmbedScheduleConfig controls when the embed worker runs on its own
// (outside of explicit `msgvault embeddings build` invocations).
type EmbedScheduleConfig struct {
	Cron         string `toml:"cron"`           // empty disables scheduled embedding
	RunAfterSync bool   `toml:"run_after_sync"` // trigger after each successful sync
}

// Fingerprint returns the "<model>:<dimension>" identifier for the
// embedding endpoint half of the policy (§6.7 of the spec). Use
// Config.GenerationFingerprint when storing or comparing index
// generations — that variant also folds in the preprocessing policy so
// flipping a strip_* toggle stales the index.
func (e EmbeddingsConfig) Fingerprint() string {
	return fmt.Sprintf("%s:%d", e.Model, e.Dimension)
}

// GenerationFingerprint returns the full identifier used to compare an
// index generation against the configured policy. Format:
// "<model>:<dimension>:<preprocess>:c<max_input_chars>:e<embed_policy>".
// Every segment is derived from the effective config (or a code-level
// version constant), so changing the embedding model/dimension, any
// preprocessing toggle, the truncation cap, or the embed-worker output
// layout produces a new fingerprint and the ResolveActiveForFingerprint
// check forces a --full-rebuild rather than silently embedding new
// messages under a policy different from the already-active vectors.
//
// max_input_chars is part of the policy because the embed worker uses
// it as the per-chunk rune cap fed into ChunkText (and, before
// chunking, as the rune-bounded truncation cap fed into Preprocess);
// raising or lowering it changes which chunks a long message produces,
// so two cap values produce two different embedding layouts and must
// not share one generation.
//
// embed_policy (the embedPolicyVersion constant) covers worker-side
// changes that shift the vector layout for the same Preprocess output
// — most notably the switch from one-vector-per-message-with-truncation
// to N-vectors-per-message-via-ChunkText. Without folding this version
// in, an active generation built under the old single-vector policy
// would silently accept new chunked entries from an upgraded worker.
func (c *Config) GenerationFingerprint() string {
	return fmt.Sprintf("%s:%s:c%d:e%d",
		c.Embeddings.Fingerprint(), c.Preprocess.Fingerprint(), c.Embeddings.MaxInputChars, embedPolicyVersion)
}

// Validate returns a descriptive error if the config is unusable.
// Only called when Enabled is true; disabled configs are not checked.
func (c *Config) Validate() error {
	// The concrete backend is selected at the command layer from the
	// database DSN (SQLite → sqlite-vec, PostgreSQL → pgvector); this
	// field is a declared marker, not the selector. Accept either known
	// backend and reject anything else.
	switch c.Backend {
	case "sqlite-vec", "pgvector":
	default:
		return fmt.Errorf("vector.backend: unknown backend %q (supported: \"sqlite-vec\", \"pgvector\")", c.Backend)
	}
	if c.Embeddings.Endpoint == "" {
		return errors.New("vector.embeddings.endpoint: required")
	}
	u, err := url.Parse(c.Embeddings.Endpoint)
	if err != nil || u.Host == "" || (u.Scheme != "http" && u.Scheme != "https") {
		return fmt.Errorf("vector.embeddings.endpoint: must be an http or https URL with a host (got %q)", c.Embeddings.Endpoint)
	}
	if c.Embeddings.Model == "" {
		return fmt.Errorf("vector.embeddings.model: required (the index generation fingerprint is %q, which is ambiguous without a model name)", c.Embeddings.Fingerprint())
	}
	if c.Embeddings.Dimension <= 0 {
		return fmt.Errorf("vector.embeddings.dimension: must be positive, got %d", c.Embeddings.Dimension)
	}
	if c.Embeddings.BatchSize <= 0 {
		return fmt.Errorf("vector.embeddings.batch_size: must be positive, got %d", c.Embeddings.BatchSize)
	}
	return nil
}

// ApplyDefaults fills in sensible defaults for any zero-valued fields.
// Called after TOML decode, before Validate.
func (c *Config) ApplyDefaults() {
	if c.Backend == "" {
		c.Backend = "sqlite-vec"
	}
	if c.Embeddings.BatchSize == 0 {
		c.Embeddings.BatchSize = 32
	}
	if c.Embeddings.Timeout == 0 {
		c.Embeddings.Timeout = 30 * time.Second
	}
	if c.Embeddings.MaxRetries == 0 {
		c.Embeddings.MaxRetries = 3
	}
	if c.Embeddings.MaxInputChars == 0 {
		c.Embeddings.MaxInputChars = 32768
	}
	if c.Embeddings.ETAWindow <= 0 {
		c.Embeddings.ETAWindow = 10
	}
	if c.Search.RRFK == 0 {
		c.Search.RRFK = 60
	}
	if c.Search.KPerSignal == 0 {
		c.Search.KPerSignal = 100
	}
	if c.Search.SubjectBoost == 0 {
		c.Search.SubjectBoost = 2.0
	}
	if c.Search.MaxPageSizeHybrid == nil {
		v := 50
		c.Search.MaxPageSizeHybrid = &v
	}
	// Preprocess booleans are *bool so unset (nil) means "default true"
	// without overwriting an explicit false from the config file. The
	// StripQuotesEnabled / StripSignaturesEnabled helpers resolve the
	// effective value.
}

// APIKey resolves the API key from the env var named in APIKeyEnv.
// Returns "" if APIKeyEnv is empty or the variable is unset.
func (e EmbeddingsConfig) APIKey() string {
	if e.APIKeyEnv == "" {
		return ""
	}
	return lookupEnv(e.APIKeyEnv)
}
